version: '2'
services:
  userservice-1-app:
    image: activemq-user:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m -Dlogging.level.root=INFO -Dspring.activemq.broker-url=tcp://activemq-service:61616 -Dapplication.name="User Service 1:"
    ports:
      - 8080:8080
  activemq-service:
    image: rmohr/activemq
    ports:
      - 8161:8161
      - 61616:61616
