spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
org:
  apache:
    activemq:
      SERIALIZABLE_PACKAGES: '*'
server:
  port: 8080

logging:
  level:
    root: INFO

application:
  name: MessageService